namespace: dev-native

resources:
  #- relayer.yaml
  - ts-relayer.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-relayer-config
    files:
      - configs/config.toml
      - configs/keys.json
  - name: test-ts-relayer-config
    files:
      - configs/ts-config.yaml
      - configs/ts-app.yaml
      - configs/ts-keys.json
