resources:
  - configmap.yaml
  - genesis.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-persistencecore
    files:
      - configs/keys.json
      - configs/validators.json
  - name: wasm-contract-persistencecore
    files:
      - configs/contract.sh
      - ../../../target/wasm32-unknown-unknown/release/simple_ica_host.wasm
