apiVersion: apps/v1
kind: Deployment
metadata:
  name: relayer
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: relayer
      app.kubernetes.io/name: relayer
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: relayer
        app.kubernetes.io/type: relayer
        app.kubernetes.io/name: relayer
        app.kubernetes.io/version: '0.1'
    spec:
      imagePullSecrets:
        - name: test-docker-creds
      containers:
        - name: relayer
          image: persistenceone/hermes:hackwasm-linux
          resources:
            limits:
              cpu: "0.5"
              memory: 0.5Gi
            requests:
              cpu: "0.1"
              memory: 0.1Gi
