resources:
  - configmap.yaml
  - genesis.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-osmosisd
    files:
      - configs/keys.json
      - configs/validators.json
