resources:
  - configmap.yaml
  - genesis.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-osmosisd
    files:
      - configs/keys.json
      - configs/validators.json
  - name: wasm-contract-osmosisd
    files:
      - configs/contract.sh
      - ../../../target/wasm32-unknown-unknown/release/simple_ica_controller.wasm
      - ../../../target/wasm32-unknown-unknown/release/callback_capturer.wasm
