apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gaiad-validator
spec:
  serviceName: gaiad-validator
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gaiad
      app.kubernetes.io/name: gaiad-validator
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: gaiad
        app.kubernetes.io/type: gaiad-validator
        app.kubernetes.io/name: gaiad-validator
        app.kubernetes.io/version: '0.1'
    spec:
      initContainers:
        - name: wait-for-genesis
          image: persistenceone/gaiad:latest
          imagePullPolicy: Always
          env:
            - name: GENESIS_HOST
              value: gaiad-genesis.default
            - name: GENESIS_PORT
              value: "8081"
        - name: init-validator
          image: persistenceone/gaiad:latest
          imagePullPolicy: Always
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain.id
                  name: gaiad
            - name: HOME_DIR
              value: /gaiad
            - name: GENESIS_HOST
              value: gaiad-genesis.default
            - name: GENESIS_PORT
              value: "8081"
          resources:
            limits:
              cpu: "0.1"
              memory: "100M"
            requests:
              cpu: "0.1"
              memory: "100M"
          volumeMounts:
            - mountPath: /gaiad
              name: gaiad
            - mountPath: /configs
              name: addresses
      containers:
        - name: validator
          image: persistenceone/gaiad
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "1G"
            requests:
              cpu: "0.1"
              memory: "500M"
        - name: exposer-app
          image: persistenceone/exposer:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.1"
              memory: "100M"
            requests:
              cpu: "0.1"
              memory: "100M"
